// js/data.js — Recipe data extracted from the Recetario PDF

const CATEGORY_LABELS = {
  aperitivos: 'Aperitivos',
  pasta:      'Pasta',
  pescados:   'Pescados',
  carnes:     'Carnes',
  arroces:    'Arroces',
  sopas:      'Sopas',
  verduras:   'Verduras',
  basicos:    'Básicos',
  bebidas:    'Bebidas',
};

const RECIPES = [
  {
    id: 'volovanes-suizos',
    title: 'Volovanes Suizos con Arroz',
    subtitle: 'Los llaman "vol-au-vent" o "pilzpastetli" en Suiza. Una receta deliciosa para visitas y como aperitivo para picar.',
    servings: 4,
    category: 'aperitivos',
    page: 4,
    ingredientGroups: [
      {
        name: 'Volovanes',
        items: [
          '4 salchichas alemanas',
          '6 volovanes',
          '½ vaso de vino dulce (Ximénez u Oporto)',
          '2 cacitos de bechamel',
        ],
      },
      {
        name: 'Guarnición',
        items: ['250 g de arroz basmati', '100 g de guisantes', '2 zanahorias'],
      },
      {
        name: 'Bechamel',
        items: [
          '200 g de harina',
          '¾ l de leche entera',
          '1 cebolla pequeña',
          'Nuez moscada',
          '50 g de mantequilla',
          'Pimienta blanca',
        ],
      },
    ],
    steps: [
      'Preparamos la bechamel semi espesa, mezclando harina con parte de la leche con una varilla. Calentamos el resto de la leche, añadimos la nuez moscada, la sal y la pimienta. Mezclamos todo y removemos.',
      'Se quitan las tapas de los volovanes y se apartan en un plato. Podemos meter los volovanes en el horno un minuto para que se gratinen ligeramente y sea más fácil cortar la tapa.',
      'Se pica la cebolla y se trocean las salchichas en pequeños trozos. También cortamos las zanahorias en juliana para la guarnición.',
      'La zanahoria ha de cocer durante 15 minutos y los diez últimos se echan los guisantes. Una vez cocido se aparta y se cuela. Cocemos también el arroz y lo apartamos.',
      'Rehogamos la cebolla con un chorrito de aceite y un poco de mantequilla a fuego medio. Una vez pochada se agregan las salchichas hasta que estén bien hechas.',
      'Se echa todo en la bechamel y se remueve bien a fuego muy bajo durante un par de minutos. Se aparta y se deja enfriar un poco.',
      'Rellenamos los volovanes con la mezcla de bechamel, cebolla y salchichas. Ponemos las tapas y metemos en el horno a 150 °C durante 10 minutos.',
      'Servimos los volovanes sobre el arroz, guisantes y zanahoria.',
    ],
    tip: {
      text: 'Al hacer la bechamel es importante que la leche no llegue a cocer. Hay que remover bien con la varilla a fuego muy bajo para evitar grumos y procurar que no se pegue. Una vez que empieza a espesar (12 minutos aproximadamente) la retiramos del fuego. Para saber que está hecha tiene que quedar blanca y no amarillenta. Usad una nuez moscada fresca que ralléis vosotros: tiene un perfume mucho más intenso.',
      author: 'Consejo de Mari',
    },
  },

  {
    id: 'salmon-marinado',
    title: 'Salmón Marinado',
    subtitle: 'Deliciosa receta de Suecia, el famoso "Gravlax". Lo hago siempre con una buena ensalada el día de Navidad.',
    servings: 4,
    category: 'pescados',
    page: 5,
    ingredientGroups: [
      {
        name: 'Salmón',
        items: ['750 g de salmón fresco'],
      },
      {
        name: 'Marinada',
        items: [
          '4 cucharadas de eneldo picado',
          '4 cucharadas de pimienta molida',
          '4 cucharadas de azúcar',
          '4 cucharadas de sal',
        ],
      },
      {
        name: 'Ensalada',
        items: [
          '1 escarola',
          '1 cucharada de mostaza',
          '1 cucharada de vinagre',
          '1 cucharada de miel',
          '1 cucharada de alcaparras',
          '8 cucharadas de aceite',
          '8 cucharadas de eneldo picado',
          'Eneldo para decorar',
        ],
      },
    ],
    steps: [
      'Limpiar el salmón de escamas dejando la piel intacta y quitar las espinas que queden con una pinza. Mezclar la sal, el azúcar, la pimienta y el eneldo, y frotar con la mezcla el salmón por la piel y por la carne.',
      'Colocar el salmón en una fuente plana, poner encima una plancha y un peso ligero dejando marinar entre 24 y 48 horas.',
      'Cortarlo en lonchas finas sesgadas, dejando 2 cm de carne con la piel.',
      'Cortar la piel del salmón en tiras y freírlas para que queden crujientes.',
      'Lavar y escurrir la ensalada, añadir la piel frita y mezclar los ingredientes del aliño.',
      'Servimos el salmón con la ensalada, el aliño y pan fresco.',
    ],
    tip: {
      text: 'Cuando compres el salmón pide que te quiten la raspa y la carne de los lados si es posible. Si no tienes una plancha puedes poner unos bricks de leche encima. Si quieres probar una mostaza algo más fuerte puedes probar la "mostaza antigua" que tiene los granos de mostaza.',
      author: 'Truco de Mari',
    },
  },

  {
    id: 'mejillones-gorgonzola',
    title: 'Mejillones al Gorgonzola',
    subtitle: 'Los italianos dicen que soñar comiendo mejillones es de buen augurio. Una variante de "moules au roquefort" con el famoso queso italiano.',
    servings: 4,
    category: 'pescados',
    page: 6,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '1 kg de mejillones',
          '2 chalotas',
          '20 g de mantequilla',
          '1 diente de ajo',
          '100 g de Martini seco',
          '150 g de nata',
          '100 g de queso gorgonzola',
          '2 yemas de huevo',
          '1 cucharada sopera de cebollino picado',
        ],
      },
    ],
    steps: [
      'Se pican las chalotas y el ajo. En una cazuela se sudan las chalotas con la mantequilla durante unos minutos, se añade el ajo bien picado y se suda todo junto otro minuto.',
      'Se agregan los mejillones y el Martini y se cuece todo a fuego vivo y tapado durante 5 minutos hasta que los mejillones se abran.',
      'Se retiran los mejillones en un plato, separando las cáscaras que tienen carne —y que conservaremos— de las que están vacías, que desecharemos.',
      'Se reduce el jugo de la cocción durante 3 minutos, se añade la nata y se hierve todo 2 minutos más.',
      'Una vez fuera del fuego se añade el gorgonzola rallado. Se mezcla todo hasta disolver bien el queso, se agregan las yemas y se vuelve a mezclar.',
      'Se pone el punto de sal y pimienta y se vierte la salsa cremosa sobre los mejillones reservados. Se espolvorea cebollino picado y se sirve.',
    ],
    tip: {
      text: 'Es importante limpiar bien los mejillones por fuera y de la rebaba que tienen. También es importante raspar las conchas con un cuchillo pequeño si tienen adherencias y limpiarlos con un cepillo fuerte. Si después de cocerlos no se abren, tiradlos. Para este plato siempre me gusta tomar un buen vino blanco fresco, por ejemplo un Rías Baixas de uva Albariño.',
      author: 'Truco de Mari',
    },
  },

  {
    id: 'col-romesco',
    title: 'Col al Horno con Salsa Romesco',
    subtitle: 'Nos gusta mucho la col y esta receta es muy sana y sirve incluso como plato único para una cena ligera.',
    servings: 4,
    category: 'verduras',
    page: 7,
    ingredientGroups: [
      {
        name: 'Para la col',
        items: [
          '1 col grande (~1 kg)',
          '2 cucharadas de aceite de oliva',
          'Sal y pimienta al gusto',
        ],
      },
      {
        name: 'Para la salsa romesco',
        items: [
          '400 g de tomates maduros',
          '1 cebolla grande',
          '200 g de pimiento rojo (opcional)',
          '3 dientes de ajo',
          '75 g de almendras tostadas',
          '50 g de pan duro',
          '50 ml de aceite de oliva',
          'Sal y pimienta al gusto',
        ],
      },
    ],
    steps: [
      'Precalentamos el horno a 200 °C. Cortamos la col en lonchas grandes de unos 5 cm de grosor.',
      'Colocamos las lonchas de col en una bandeja de horno y rociamos con aceite de oliva, sal y pimienta al gusto.',
      'En otra bandeja colocamos los tomates, el pimiento rojo, la cebolla y los dientes de ajo pelados. Rociamos con aceite de oliva y una pizca de sal.',
      'Asamos la col y los vegetales en el horno: 15 minutos para los vegetales del romesco y 30 para la col. Sacamos cuando estén tiernos y un poco chamuscados. Dejamos enfriar lo suficiente para manejarlos.',
      'Pelamos la piel de los tomates y del pimiento rojo, y retiramos las semillas del pimiento.',
      'En una batidora mezclamos los tomates, el pimiento rojo, los dientes de ajo, las almendras, el pan remojado y ¼ taza de aceite de oliva. Trituramos hasta obtener una salsa suave. Sazonamos con sal y pimienta.',
      'Colocamos la col asada en un plato grande, cubrimos con una generosa porción de salsa romesco y servimos caliente.',
    ],
    tip: {
      text: 'La salsa romesco se puede hacer añadiendo albahaca fresca. Al meter la col en el horno, ponemos la loncha boca-arriba para que se abra como una flor. Una vez horneada, quitamos las hojas externas que pueden estar un poco quemadas.',
      author: 'Truco de Vale',
    },
  },

  {
    id: 'cerdo-navidad',
    title: 'Cerdo de Navidad',
    subtitle: 'Plato especial para el invierno en la sierra.',
    servings: 4,
    category: 'carnes',
    page: 8,
    incomplete: true,
    ingredientGroups: [],
    steps: [],
    tip: null,
  },

  {
    id: 'tjvjik-pollo',
    title: 'Tjvjik de Pollo',
    subtitle: 'Receta de casquería con ingredientes que ya no se usan. Un plato muy particular y nutritivo que le encanta a los niños.',
    servings: 4,
    category: 'carnes',
    page: 9,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '400 g de mollejas de pollo',
          '400 g de corazones de pollo',
          '400 g de hígado de pollo',
          '1 cucharada de aceite de oliva',
          '2 cebollas grandes, picadas en trozos pequeños',
          '2 dientes de ajo, picados finamente',
          '1 bote de tomate Mutti',
          'Perejil y cebollino fresco para decorar',
          'Tomillo seco',
          'Romero seco',
          'Sal y pimienta',
        ],
      },
    ],
    steps: [
      'Lava y seca las mollejas, corazones e hígados de pollo. Corta todos los ingredientes por la mitad. Salpimentamos y reservamos.',
      'En una cazuela sofreímos la cebolla picada muy fina hasta que esté suave y dorada. Cuando esté dorada añadimos el tomate y bajamos el fuego.',
      'Añadimos las mollejas, los hígados y los corazones junto con las especias. Cocinamos a fuego muy bajo durante 5-6 horas.',
      'Mover cuidadosamente para asegurarse de que todos los ingredientes estén bien mezclados. Repetir cada par de horas evitando que se pegue.',
      'Sazona con sal y pimienta negra al gusto. Ajusta según sea necesario.',
      'Preparamos el arroz cuando quede poco tiempo para servir.',
      'Sirve el Tjvjik caliente, espolvoreado con perejil o cebollino fresco picado. Se puede poner el arroz en un lateral del plato o en un bol aparte.',
    ],
    tip: {
      text: 'Podemos añadir un poco de guindilla para dar algo de picante. Otras recetas usan limón seco rallado y albahaca seca.',
      author: 'Truco de Jaime',
    },
  },

  {
    id: 'sashimi-arroz',
    title: 'Sashimi y Arroz',
    subtitle: 'Una de las recetas japonesas favoritas de la familia. Pescado fresco en crudo con arroz de sushi bien preparado.',
    servings: 4,
    category: 'pescados',
    page: 11,
    ingredientGroups: [
      {
        name: 'Sashimi',
        items: [
          '300 g de filetes de pescado crudo fresco de alta calidad (atún, salmón, pez mantequilla…)',
          '1 rábano daikon, pelado y rallado finamente',
          '¼ taza de salsa de soja',
          'Wasabi al gusto',
        ],
      },
      {
        name: 'Arroz',
        items: [
          '2 tazas de arroz japonés de grano corto',
          '2¼ tazas de agua',
          '¼ taza de vinagre de arroz',
          '2 cucharadas de azúcar',
          '½ cucharadita de sal',
        ],
      },
    ],
    steps: [
      'Enjuaga el arroz en un colador bajo agua fría hasta que el agua salga clara para eliminar el exceso de almidón.',
      'Coloca el arroz en una cacerola y agrega el agua. Lleva a ebullición, reduce el fuego al mínimo, cubre y cocina a fuego lento durante 20 minutos.',
      'Apaga el fuego y deja que el arroz repose, cubierto, durante 10 minutos.',
      'Calienta el vinagre de arroz, el azúcar y la sal en una cacerola pequeña hasta que se disuelvan. Deja enfriar a temperatura ambiente.',
      'Traslada el arroz cocido a un tazón grande y rocía la mezcla de vinagre. Usa una espátula de madera para mezclar sin presionar. Deja enfriar a temperatura ambiente.',
      'Corta los filetes de pescado en rodajas finas y uniformes de 0,5 a 1 cm de grosor.',
      'Dispón el sashimi en un plato de servir y coloca el rábano daikon rallado junto al pescado. Sirve con soja y wasabi.',
    ],
    tip: {
      text: 'Usa siempre pescado de la máxima calidad y frescura, apto para consumo en crudo. El daikon rallado limpia el paladar entre bocados.',
      author: 'Truco de Jaime',
    },
  },

  {
    id: 'nabe',
    title: 'Nabe (Hotpot Japonés)',
    subtitle: 'Plato reconfortante para las noches de invierno. El hotpot japonés reúne a la familia alrededor de la mesa.',
    servings: 4,
    category: 'sopas',
    page: 12,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '500 g de carne de res en cortes finos',
          '500 g de mariscos mixtos (camarones, pulpo, calamares)',
          '1 taza de champiñones frescos en rodajas',
          '1 taza de hojas de espinaca',
          '½ taza de cebolla verde picada',
          '1 zanahoria grande, en rodajas delgadas',
          '1 nabo, en rodajas delgadas',
          '1 taza de brotes de soja',
          '1 paquete de tofu firme en cubos',
          '2 dientes de ajo finamente picados',
          '½ taza de salsa de soja',
          '2 cucharadas de sake japonés (opcional)',
          '1 cucharada de aceite vegetal',
          'Cilantro fresco picado para decorar',
        ],
      },
    ],
    steps: [
      'Coloca una olla grande en el fuego. Agrega el aceite y caliéntalo. Agrega el ajo y fríe por un minuto hasta que esté fragante.',
      'Añade la carne de res y fríela hasta que esté dorada. Agrega la salsa de soja y el sake y cocina por unos minutos más.',
      'Agrega los mariscos, champiñones, zanahorias, nabos y brotes de soja. Vierte agua hasta cubrir los ingredientes y deja que el caldo se cocine a fuego medio-alto durante 10 minutos (retira la espuma ocasionalmente).',
      'Agrega las hojas de espinaca y los cubos de tofu. Cocina unos minutos más hasta que las espinacas se marchiten y el tofu esté caliente.',
      'Decora con cebolla verde picada y cilantro fresco si lo deseas. Sirve la nabe caliente en platos hondos.',
    ],
    tip: {
      text: 'Este plato se sirve en la propia olla en el centro de la mesa, y cada comensal se sirve a su gusto. Puedes añadir fideos ramen o udon al final de la cocción.',
      author: 'Truco de Alberto',
    },
  },

  {
    id: 'tagliatelle-vongole',
    title: 'Tagliatelle alle Vongole',
    subtitle: 'Ésta receta está avalada por mi hermano como "la mejor pasta que ha comido nunca".',
    servings: 4,
    category: 'pasta',
    page: 14,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '500 g de pasta tagliatelle',
          '90 ml de aceite de oliva',
          '1 cucharada sopera de ajo picado fino',
          '1 cucharada sopera de perejil fresco picado',
          '48 almejas o berberechos frescos',
          '90 ml de vino blanco',
          '30 g de mantequilla',
          'Una pizca minúscula de guindilla',
        ],
      },
    ],
    steps: [
      'Sumergir las almejas en agua salada durante 10 minutos para que suelten la arena. Escurrirlas para quitar la sal.',
      'Usamos una sartén de hierro colado grande y plana para sofreír el ajo y añadimos una vez dorado la guindilla y el perejil.',
      'Agregamos las almejas con sus conchas y añadimos el vino. Cocinamos medio minuto para que se evapore el vino y tapamos la sartén para que se cocinen con el vapor.',
      'Controlando con frecuencia, cocinaremos hasta que todas se hayan abierto. Apagamos el fuego y dejamos reposar. Retiramos la mitad de las conchas dejando la carne de la almeja.',
      'Mientras se cocinan llenamos una olla con agua y un puñado de sal marina y ponemos a hervir la pasta.',
      'Un minuto antes de su punto al dente retiramos y colamos la pasta, encendemos el fuego en la sartén de las almejas y terminamos la cocción de la pasta en ella.',
      'Añadimos la mantequilla y removemos hasta que la pasta esté al dente.',
    ],
    tip: {
      text: 'Recordad que hay que eliminar las almejas que vengan abiertas o rotas de la compra. Una vez cocidas hay que quitar las que no se hayan abierto. Es importante cocinar la pasta con la salsa al mismo tiempo para que absorba el jugo de las almejas.',
      author: 'Truco de Jaime',
    },
  },

  {
    id: 'gnocchi-ragu',
    title: 'Gnocchi con Ragú',
    subtitle: 'Posiblemente la comida favorita de mi hijo, un plato reconfortante para gente hambrienta.',
    servings: 4,
    category: 'pasta',
    page: 15,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '500 g de ñoquis de patata',
          '250 g de carne de cerdo picada',
          '250 g de carne de vaca picada',
          '500 g de tomates pelados',
          '150 ml de vino blanco',
          '1 cebolla',
          '1 zanahoria',
          'Medio bote de tomate Mutti',
          'Grana o parmesano',
          'Aceite de oliva virgen extra',
          'Sal y pimienta',
        ],
      },
    ],
    steps: [
      'Corta finamente la cebolla y sofríela a fuego lento en una olla con un generoso chorro de aceite de oliva virgen extra. Añade la zanahoria rallada fina.',
      'Agrega la carne picada y desmenúzala con una cuchara de madera, sazona al gusto y sofríe. Cuando la carne esté bien dorada, sube el fuego y cocina con el vino blanco.',
      'Una vez que el vino se haya evaporado, añade el tomate Mutti. Reduce el fuego, cubre con una tapa y cocina unos minutos removiendo de vez en cuando.',
      'Agrega los tomates pelados, sazona con sal y pimienta, y continúa cocinando durante aproximadamente 3 horas a fuego muy lento. Una vez que el ragú esté listo, apaga el fuego y deja reposar.',
      'Cocina los ñoquis en abundante agua hirviendo. Cuando comiencen a flotar, retíralos con una espumadera y agrégales el ragú caliente. Mezcla para integrar y sirve bien calientes.',
      'Espolvorea con parmesano o grana al gusto. Puedes poner unas hojitas de albahaca para decorar.',
    ],
    tip: {
      text: 'Hay que asegurarse de que el ragú no tenga pegotes de carne, así que tómate tu tiempo con la cuchara de madera hasta que esté todo homogéneo. Uso el tomate Mutti porque me gusta como queda; también puedes usar concentrado de tomate disuelto en agua.',
      author: 'Truco de Jaime',
    },
  },

  {
    id: 'canelones-atun',
    title: 'Canelones de Atún',
    subtitle: 'La receta de mi madre. Un clásico de la cocina familiar española.',
    servings: 4,
    category: 'pasta',
    page: 16,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '12 placas de pasta para canelones',
          '2 latas de atún en aceite (~300 g en total)',
          '1 cebolla mediana, picada',
          '2 dientes de ajo, picados',
          '1 pimiento rojo, en cubitos (opcional)',
          '400 g de tomate triturado',
          '1 cucharada de aceite de oliva',
          'Sal y pimienta al gusto',
          'Queso rallado para gratinar',
          'Bechamel (igual que en los volovanes)',
        ],
      },
    ],
    steps: [
      'Precalienta el horno a 180 °C.',
      'Hierve las placas de canelones en agua con sal hasta que estén al dente. Escurre y colócalas sobre papel de cocina separadas para evitar que se peguen.',
      'Calienta el aceite en una sartén a fuego medio. Añade la cebolla y el ajo y cocina hasta que estén suaves y transparentes, aproximadamente 5 minutos.',
      'Agrega el pimiento rojo (si lo usas) y cocina 3-4 minutos más.',
      'Desmenuza el atún y agrégalo a la sartén junto con el tomate triturado. Cocina a fuego lento durante 10 minutos, removiendo de vez en cuando. Sazona con sal y pimienta.',
      'Prepara la bechamel: derrite la mantequilla, añade la harina y mezcla bien un minuto. Vierte la leche gradualmente removiendo constantemente hasta que espese. Sazona con sal, pimienta y nuez moscada.',
      'En cada placa de canelón, coloca una porción del relleno de atún y enrolla para formar un cilindro. Repite para todos los canelones.',
      'Coloca los canelones en una fuente de horno, cúbrelos con la bechamel, espolvorea queso rallado y hornea 20-25 minutos hasta que el queso esté dorado.',
    ],
    tip: {
      text: 'Este plato marida bien con un buen Rioja.',
      author: 'Truco de Mari',
    },
  },

  {
    id: 'pizza-napolitana',
    title: 'Pizza Napolitana',
    subtitle: 'La auténtica pizza napolitana, con masa de larga fermentación y tomate San Marzano.',
    servings: 4,
    category: 'pasta',
    page: 17,
    ingredientGroups: [
      {
        name: 'Masa',
        items: [
          '500 g de harina de trigo de fuerza (tipo 00)',
          '325 ml de agua tibia',
          '10 g de sal',
          '2 g de levadura seca activa',
        ],
      },
      {
        name: 'Salsa de tomate',
        items: [
          '400 g de tomates San Marzano pelados y triturados',
          '1 diente de ajo picado (opcional)',
          'Sal, pimienta y ½ cucharadita de azúcar al gusto',
          '1 cucharada de aceite de oliva',
        ],
      },
      {
        name: 'Toppings',
        items: [
          '250 g de mozzarella fresca, escurrida y en rodajas (preferiblemente de búfala)',
          'Albahaca fresca al gusto',
          'Aceite de oliva extra virgen al gusto',
        ],
      },
    ],
    steps: [
      'Mezcla la harina, la levadura y la sal. Agrega el agua tibia lentamente mientras mezclas, hasta que se forme una masa blanda. Amasa por 10-15 minutos hasta obtener una masa elástica y suave.',
      'Deja reposar la masa en un recipiente engrasado cubierto con un paño húmedo. Déjala fermentar 2 horas o hasta que doble su tamaño en un lugar cálido.',
      'Mezcla los tomates triturados, el ajo, el aceite de oliva, la sal, la pimienta y el azúcar en un tazón. Reserva.',
      'Precalienta el horno a 250 °C con una piedra para pizza en la rejilla inferior durante al menos 30 minutos.',
      'Divide la masa en dos porciones. Sobre una superficie enharinada, aplana cada porción con los dedos hasta unos 30 cm de diámetro, dejando el borde un poco más grueso.',
      'Cubre la masa con una capa fina de salsa de tomate (dejando 1-2 cm de borde) y coloca rodajas de mozzarella con espacio entre ellas.',
      'Hornea 8-10 minutos hasta que los bordes estén dorados y la mozzarella burbujee. Termina con albahaca fresca y un hilo de aceite de oliva.',
    ],
    tip: {
      text: 'La clave está en la temperatura: el horno debe estar al máximo. Cuanto más alta la temperatura, más auténtica quedará la pizza. La piedra para pizza marcará la diferencia en la base.',
      author: 'Truco de Alberto',
    },
  },

  {
    id: 'albondigas-salsa',
    title: 'Albóndigas en Salsa',
    subtitle: 'Receta de Max Mariola. Albóndigas jugosas en salsa de tomate casera, un clásico reconfortante.',
    servings: 4,
    category: 'carnes',
    page: 18,
    ingredientGroups: [
      {
        name: 'Albóndigas',
        items: [
          '500 g de carne de vaca picada',
          '½ taza de pan rallado',
          '¼ taza de queso parmesano rallado',
          '¼ taza de perejil fresco picado',
          '2 dientes de ajo finamente picados',
          '1 huevo grande',
          '½ cucharadita de sal',
          '½ cucharadita de pimienta negra molida',
          'Aceite de oliva para freír',
        ],
      },
      {
        name: 'Salsa de tomate',
        items: [
          '1 lata de tomates pelados enteros (400 g)',
          '3 dientes de ajo finamente picados',
          '1 cebolla mediana picada',
          '2 cucharadas de aceite de oliva',
          '1 cucharadita de azúcar',
          '1 cucharadita de sal',
          '1 cucharadita de orégano seco',
        ],
      },
    ],
    steps: [
      'En un tazón grande, combina la carne picada, pan rallado, parmesano, perejil, ajo, huevo, sal y pimienta. Mezcla bien hasta integrar todos los ingredientes.',
      'Forma albóndigas del tamaño de una pelota de golf. Deberías obtener cerca de 12 unidades.',
      'En una sartén grande, calienta 2 cucharadas de aceite a fuego medio-alto. Cocina las albóndigas por todos lados hasta que estén doradas. Retíralas y reserva.',
      'En la misma sartén añade el aceite. Añade la cebolla picada y el ajo, cocinándolos hasta que estén suaves, aproximadamente 3 minutos.',
      'Añade los tomates, el azúcar, la sal y el orégano. Mezcla bien y cocina la salsa 10 minutos a fuego medio-bajo hasta que espese.',
      'Coloca las albóndigas doradas en la salsa de tomate. Cocina a fuego lento durante 25-30 minutos hasta que las albóndigas estén completamente cocidas.',
      'Sirve caliente con pasta o pan para mojar en la salsa.',
    ],
    tip: {
      text: 'Este plato marida bien con un buen Rioja. Puedes añadir unas hojas de albahaca fresca al final para más aroma.',
      author: 'Truco de Mari',
    },
  },

  {
    id: 'tartufo-huevo',
    title: 'Tartufo Bianco con Huevo Frito',
    subtitle: 'La trufa blanca es uno de los ingredientes más preciados de la cocina italiana. Un plato sencillo que deja boquiabierto.',
    servings: 2,
    category: 'basicos',
    page: 19,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '2 huevos grandes',
          '2 rebanadas de pan (preferiblemente baguette o pan rústico)',
          '2 cucharadas de aceite de oliva',
          '1 trufa blanca (tartufo bianco) fresca, ~20-30 g',
          'Sal y pimienta al gusto',
        ],
      },
    ],
    steps: [
      'Calienta una sartén antiadherente a fuego medio y añade 1 cucharada de aceite de oliva.',
      'Cuando el aceite esté caliente, tuesta las rebanadas de pan por ambos lados hasta que estén doradas. Retira y reserva.',
      'En la misma sartén, añade la otra cucharada de aceite de oliva. Casca los huevos en la sartén y fríe a fuego medio hasta que la clara cuaje y las yemas queden semi-líquidas.',
      'Mientras se fríen los huevos, lava y seca la trufa blanca. Rállala en láminas finas con un rallador de trufa y reserva.',
      'Coloca las rebanadas de pan tostado en platos individuales y coloca cada huevo frito encima.',
      'Adereza con las láminas finas de trufa blanca repartidas entre los dos platos. Salpimienta ligeramente y sirve inmediatamente.',
    ],
    tip: {
      text: 'La trufa blanca es muy delicada y no debe cocinarse. Siempre se ralla en crudo sobre el plato caliente justo antes de servir. Este es un plato de temporada que funciona mejor con trufa recién cosechada.',
      author: 'Truco de Alberto',
    },
  },

  {
    id: 'tagliolini-tartufo',
    title: 'Tagliolini al Tartufo Bianco',
    subtitle: 'Durante el Covid… un plato elegantísimo con pocos ingredientes y la trufa blanca como protagonista.',
    servings: 2,
    category: 'pasta',
    page: 20,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '250 g de tagliolini frescos',
          '1 trufa blanca (tartufo bianco) fresca, ~20-30 g',
          '2 cucharadas de mantequilla sin sal',
          '½ taza de queso Parmigiano-Reggiano rallado',
          'Sal al gusto',
        ],
      },
    ],
    steps: [
      'Llena una olla con agua abundante y añade sal generosa. Lleva a ebullición.',
      'Mientras esperas, lava y seca la trufa blanca. Rállala en láminas finas con un rallador de trufa y reserva.',
      'Añade los tagliolini frescos al agua hirviendo y cocínalos según las instrucciones del paquete, generalmente 2-3 minutos.',
      'Mientras la pasta se cocina, derrite la mantequilla en una sartén grande a fuego medio.',
      'Cuando la pasta esté cocida, escúrrela y añádela a la sartén con la mantequilla derretida. Mezcla bien para que la pasta quede completamente cubierta.',
      'Espolvorea el queso Parmigiano-Reggiano rallado sobre la pasta y mezcla nuevamente.',
      'Sirve la pasta en platos individuales y adereza con las láminas finas de trufa blanca. Sirve inmediatamente.',
    ],
    tip: {
      text: 'La sencillez es la clave de este plato. No le añadas nada más —ni ajo, ni aceite extra— para que la trufa sea la verdadera protagonista. Sirve en platos precalentados.',
      author: 'Truco de Jaime',
    },
  },

  {
    id: 'spaghetti-carbonara',
    title: 'Spaghetti alla Carbonara',
    subtitle: 'La auténtica carbonara romana: sin nata, con guanciale y la mezcla perfecta de huevo y pecorino.',
    servings: 4,
    category: 'pasta',
    page: 21,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '400 g de spaghetti',
          '150 g de guanciale (o panceta si no se encuentra guanciale)',
          '3 huevos grandes',
          '1 yema de huevo adicional',
          '½ taza de queso Pecorino Romano rallado',
          '¼ taza de queso Parmigiano-Reggiano rallado',
          'Pimienta negra recién molida al gusto',
          'Sal para cocinar la pasta',
        ],
      },
    ],
    steps: [
      'En una olla grande, hierve agua con sal. Corta el guanciale en láminas o cubos pequeños.',
      'Cocina el guanciale a fuego medio-bajo hasta que esté dorado y crujiente, 5-7 minutos. Retira del fuego y reserva el guanciale junto con la grasa que soltó.',
      'En un tazón, mezcla los huevos, la yema adicional y los quesos. Bate enérgicamente. Añade pimienta negra recién molida al gusto.',
      'Cocina el spaghetti hasta que esté al dente. Antes de escurrir, reserva aproximadamente 1 taza del agua de cocción.',
      'Escurre el spaghetti y viértelo en la sartén con el guanciale y su grasa. Agrega la mezcla de huevo y queso y mezcla rápidamente para que se forme una salsa cremosa.',
      'Si la salsa está demasiado espesa, añade un poco del agua de cocción reservada, unos 30 ml a la vez.',
      'Sirve caliente, espolvoreado con más pimienta negra y queso rallado si lo deseas.',
    ],
    tip: {
      text: 'El secreto está en la temperatura: la sartén no debe estar demasiado caliente cuando añades los huevos o se cuajarán. La grasa del guanciale es fundamental para la textura de la salsa. Nunca uses nata —eso no es carbonara.',
      author: 'Truco de Alberto',
    },
  },

  {
    id: 'pasta-cacio-pepe',
    title: 'Pasta Cacio e Pepe',
    subtitle: 'Pasta rápida que te saca de un apuro con pocos ingredientes. Muy reconfortante pero nada ligera.',
    servings: 2,
    category: 'pasta',
    page: 22,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '250 g de pasta (spaghetti o bucatini)',
          '1 taza de queso Pecorino Romano rallado fino',
          '1 cucharadita de pimienta negra recién molida',
          '2 cucharadas de mantequilla',
          'Sal al gusto',
        ],
      },
    ],
    steps: [
      'Hierve una olla grande de agua y añade sal generosamente. Cocina la pasta hasta 1 minuto antes de que esté al dente. Reserva aproximadamente 1 taza del agua de cocción antes de escurrir.',
      'Mientras la pasta se cocina, derrite la mantequilla en una sartén grande a fuego medio.',
      'Agrega la pimienta negra recién molida a la mantequilla derretida y revuelve unos minutos hasta que se libere su fragancia.',
      'Escurre la pasta y transfié rela a la sartén con la mantequilla y la pimienta. Mezcla bien.',
      'Agrega lentamente el queso Pecorino Romano rallado, revolviendo constantemente para crear una salsa cremosa. Si está demasiado espesa, agrega un poco del agua de cocción reservada.',
      'Prueba y ajusta la sal con cuidado, ya que el queso Pecorino ya es bastante salado.',
    ],
    tip: {
      text: 'Usa el rallador fino y ten cuidado de que no queden pegotes de queso. También se puede tostar la pimienta negra antes de molerla para más aroma. Procurar llevar camisa al cocinar porque el queso quema.',
      author: 'Truco de Jaime',
    },
  },

  {
    id: 'minihamburguesas-pavo',
    title: 'Minihamburguesas de Pavo',
    subtitle: 'Pequeñas hamburguesas de pavo, perfectas como aperitivo o para los más pequeños.',
    servings: 4,
    category: 'carnes',
    page: 24,
    incomplete: true,
    ingredientGroups: [],
    steps: [],
    tip: null,
  },

  {
    id: 'cazuela-arroz-pollo',
    title: 'Cazuela de Arroz con Pollo',
    subtitle: 'Ésta receta es de Yotam Ottolenghi, la hago mucho en casa porque es facilísima y nos encanta a todos.',
    servings: 4,
    category: 'arroces',
    page: 25,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '1,5 kg de pollo troceado en 6-8 partes',
          '2 cebollas grandes',
          '200 g de arroz',
          'Aceite de oliva',
          '2 ramas de canela',
          'Comino',
          '3 clavos enteros',
          '10 vainas de cardamomo',
          'Pimienta negra',
          'Sal al gusto',
          '75 g de pasas',
          'Puñados de cilantro y eneldo frescos picados',
          '200 ml de agua',
        ],
      },
    ],
    steps: [
      'Mezclamos con las manos las piezas de pollo con aceite de oliva, sal, pimienta negra en cantidad, cardamomo, clavo y las ramas de canela partidas por la mitad. Dejamos reposar mientras seguimos cocinando.',
      'Usamos una cazuela o sartén amplia con tapa, preferiblemente de hierro colado. Caramelizamos la cebolla en aceite de oliva hasta que esté dorada. Retiramos y reservamos.',
      'En la misma sartén con un poco de aceite cocinamos el pollo con las especias a fuego medio, 5 minutos cada lado para que esté bien dorado y crujiente. Retiramos y reservamos.',
      'Agregamos el arroz, la cebolla y las pasas a la cazuela donde se cocinó el pollo y removemos cocinándolo 1-2 minutos para que se impregne del sabor. Añadimos sal y más pimienta.',
      'Colocamos las piezas de pollo sobre el arroz y echamos el agua caliente. Tapamos y cocinamos a fuego muy bajo durante 30 minutos, hasta que el arroz esté tierno y el pollo completamente cocido.',
      'Dejamos reposar con un paño bajo la tapa un par de minutos y servimos. Podemos adornar con cilantro fresco picado.',
    ],
    tip: {
      text: 'Usa pimienta fresca molida. Es importante que la medida de agua sea exacta para esta receta. Yo uso pasas por simplicidad pero también se pueden usar grosellas en azúcar. Cuidado al romper la canela: buscamos un par de trozos grandes, no fragmentos pequeños.',
      author: 'Truco de Jaime',
    },
  },

  {
    id: 'trucha-calabacin',
    title: 'Trucha con Calabacín',
    subtitle: 'Plato ligero y saludable de trucha con calabacín, perfecto para el verano.',
    servings: 4,
    category: 'pescados',
    page: 26,
    incomplete: true,
    ingredientGroups: [],
    steps: [],
    tip: null,
  },

  {
    id: 'gazpacho',
    title: 'Gazpacho',
    subtitle: 'Plato fresquísimo para el verano que le encanta a Valentina. Sencillo de hacer y además no se tarda nada en prepararlo.',
    servings: 4,
    category: 'sopas',
    page: 28,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '1 kg de tomates maduros, cortados en cuartos',
          '1 pimiento verde, sin semillas y cortado en trozos grandes',
          '1 pepino pelado, cortado por la mitad y sin semillas',
          '½ cebolla pequeña, picada',
          '2 dientes de ajo, picados',
          '1 rebanada de pan de molde sin corteza, remojada en agua y escurrida',
          '3 tazas (750 ml) de agua fría',
          '⅓ taza (80 ml) de aceite de oliva virgen extra',
          '2 cucharadas de vinagre de vino tinto',
          'Sal y pimienta al gusto',
          'Guarnición: pimientos, pepino, cebolla y pan crujiente en cubos',
        ],
      },
    ],
    steps: [
      'En una licuadora o procesador de alimentos, combina los tomates, el pimiento verde, el pepino, la cebolla y el ajo. Licúa hasta obtener una mezcla suave y uniforme.',
      'Añade la rebanada de pan remojada y escurrida a la mezcla de vegetales. Licúa nuevamente hasta que quede bien mezclado.',
      'Mientras la licuadora esté en marcha, vierte el aceite de oliva y el vinagre en la mezcla en un hilo fino. Continúa licuando hasta que esté bien emulsionado.',
      'Transfiere el gazpacho a un recipiente grande y diluye con las 3 tazas de agua fría, mezclando bien.',
      'Sazona con sal y pimienta al gusto. Cubre el recipiente y refrigera durante unas 2 horas antes de servir.',
      'Sirve el gazpacho frío en tazones o copas individuales con la guarnición de pimientos, pepino, cebolla y pan crujiente.',
    ],
    tip: {
      text: 'Los tomates han de estar bien maduros, eso marca la diferencia. También se puede colar para hacerlo más suave. No escatimes en aceite de oliva de calidad.',
      author: 'Truco de Mari',
    },
  },

  {
    id: 'crema-zanahorias',
    title: 'Crema de Zanahorias',
    subtitle: 'Una crema sencillísima que funciona siempre. Suave, reconfortante y de bonito color naranja.',
    servings: 4,
    category: 'sopas',
    page: 29,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '4 zanahorias grandes',
          '1 patata',
          'Parte blanca de 1 puerro',
          '2 cucharadas de aceite de oliva',
          '1 cucharadita de jengibre fresco rallado (opcional)',
          '½ taza de crema de leche o leche (opcional)',
          'Sal y pimienta al gusto',
          'Cilantro o perejil fresco picado para decorar',
        ],
      },
    ],
    steps: [
      'Pela y cuece las zanahorias y las patatas. Cuando las zanahorias empiezan a estar blandas retira todo del fuego. No las cuezas demasiado para que la crema tenga un sabor más fresco.',
      'En una batidora echa todo, incluyendo un vaso del caldo de cocer.',
      'Si deseas añadir jengibre, rállalo e incorpóralo en este momento. Dale a la batidora y mezcla todo bien.',
      'Si deseas añadir crema de leche o leche, incorpórala ahora y mezcla bien. Ajusta la sal y pimienta al gusto.',
      'Sirve la crema caliente, decorada con cilantro o perejil fresco picado.',
    ],
    tip: {
      text: 'Puedes pasarla por un tamiz antes de servir pero es innecesario en mi opinión, ya que no quedan fibras que tamizar.',
      author: 'Truco de Jaime',
    },
  },

  {
    id: 'pan-casero',
    title: 'Pan Casero',
    subtitle: 'El placer de hornear tu propio pan en casa. Durante el Covid descubrimos lo reconfortante que es.',
    servings: 4,
    category: 'basicos',
    page: 30,
    incomplete: true,
    ingredientGroups: [],
    steps: [],
    tip: null,
  },

  {
    id: 'cocido-madrileno',
    title: 'Cocido Madrileño',
    subtitle: 'Plato completo que puede durar varios días. Se lleva haciendo en España desde antes del s. XV y en mi casa toda la vida.',
    servings: 4,
    category: 'arroces',
    page: 31,
    ingredientGroups: [
      {
        name: 'Cocido',
        items: [
          '300 g de garbanzos',
          '½ repollo',
          '300 g de morcillo o culata de vaca',
          'Media pechuga de pollo',
          '1 chorizo',
          '1 morcilla de arroz',
          '150 g de tocino veteado',
          'Punta de jamón',
          '1 hueso de jamón y otro de caña de vaca',
          '3 patatas',
          '3 zanahorias',
          '3 dientes de ajo',
          'Aceite, sal, perejil y azafrán',
        ],
      },
      {
        name: 'Sopa',
        items: ['Caldo de cocido', 'Fideos finos'],
      },
    ],
    steps: [
      'Se dejan remojar los garbanzos desde la noche anterior (unas 12 horas).',
      'En una olla grande se echa agua fría, la carne, el codillo, el tocino y los huesos junto con las especias. El chorizo y la morcilla los haremos luego aparte.',
      'Cuando empieza a hervir se añaden los garbanzos (se pueden meter en una red especial para que cuezan separados).',
      'Una vez hierva se baja el fuego y una hora más tarde se añade el pollo, quitamos la espuma y dejamos cocer. En total debe cocer durante 3 horas y media.',
      'Una hora antes de terminar se echan las zanahorias peladas y troceadas y media hora antes las patatas peladas pero enteras.',
      'Se aparta un poco de caldo en otra cazuela, se limpia y pica el repollo. Añadimos el chorizo y la morcilla, se tapa y se cuece aparte.',
      'Con el caldo que queda se puede hacer una sopa espectacular: simplemente se echan los fideos en el caldo y se dejan cocer 8 minutos.',
      'El cocido se sirve en dos fuentes, una con las verduras y los garbanzos y otra para la carne. Se acompaña con salsa de tomate.',
    ],
    tip: {
      text: 'Para el cocido valen otros tipos de carne, por ejemplo las manitas de cerdo en vez del tocino. El pollo es perfecto para hacer croquetas al día siguiente. En una olla express se hace en una hora y quince minutos.',
      author: 'Truco de Mari',
    },
  },

  {
    id: 'lentejas-chorizo',
    title: 'Lentejas con Chorizo',
    subtitle: 'Es una receta sencilla y digna de reyes. Nada más rico que las lentejas para el comienzo del frío y además son súper nutritivas.',
    servings: 4,
    category: 'arroces',
    page: 32,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '300 g de lentejas pardinas extra',
          '2 zanahorias grandes',
          '2 dientes de ajo',
          '½ cebolla grande',
          '2 hojas de laurel',
          '½ cucharada de pimentón de la Vera',
          'Sal y pimienta al gusto',
          '2 cucharadas de aceite de oliva virgen extra',
          '½ pimiento rojo',
          '1 tomate',
          '1 patata',
          '1 chorizo (80 g)',
          '¼ hueso de jamón (~70 g)',
          'Toque de curry y de comino',
        ],
      },
    ],
    steps: [
      'Calentamos previamente agua suficiente como para cubrir las lentejas y 2-3 dedos más según como las queramos de caldosas.',
      'Cocemos el tomate y le quitamos la piel. No lo echamos aún ya que tiene mucha agua.',
      'En una cazuela echamos un chorrito de aceite, la cebolla, los dientes de ajo, la zanahoria y el pimiento bien picados. Sofreímos todo durante 5 minutos, bajamos el fuego y dejamos que se rehogue hasta que esté todo blando.',
      'Echamos las lentejas y rehogamos el contenido. Añadimos sal, pimienta blanca, toque de curry y toque de comino. Añadimos también la hoja de laurel.',
      'Añadimos el hueso, la patata troceada, el chorizo y una cucharada pequeña de pimentón de la Vera dulce. Hervimos a fuego bajo para evitar que se arrebaten.',
      'Mientras hierven retiramos la espuma que contiene impurezas. Hervirán durante unos 30 minutos; removemos de vez en cuando y vigilamos el punto de sal y el agua.',
      'Al final de la cocción casi no notaremos textura de ninguno de los ingredientes pero sí su sabor.',
    ],
    tip: {
      text: 'Si usas la lenteja pardina no hace falta dejarlas en remojo antes. Como el ajo a muchas personas no les gusta encontrarlo en el plato, podéis echarlo entero y retirarlo a mitad de la cocción.',
      author: 'Truco de Mari',
    },
  },

  {
    id: 'tortilla-patatas',
    title: 'Tortilla de Patatas',
    subtitle: 'El clásico de clásicos de la cocina española. Con o sin cebolla, jugosa por dentro.',
    servings: 4,
    category: 'basicos',
    page: 33,
    incomplete: true,
    ingredientGroups: [],
    steps: [],
    tip: null,
  },

  {
    id: 'patatas-revolconas',
    title: 'Patatas Revolconas',
    subtitle: 'La abuela Jacinta lo preparaba en Narros del Puerto (Ávila) y muy bien, con carne de matanza. De origen humilde, era tradicional por sus pocos ingredientes.',
    servings: 4,
    category: 'basicos',
    page: 34,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '1½ kg de patatas',
          '3 hojas de laurel',
          '1 diente de ajo',
          'Ajo en polvo',
          '125 g de panceta',
          '½ chorizo (125 g)',
          '1 cucharadita de pimentón dulce',
          'Aceite',
          'Sal',
        ],
      },
    ],
    steps: [
      'Pelar, lavar y trocear las patatas.',
      'Cocemos durante unos 30 minutos en abundante agua las patatas, el ajo, la sal y el laurel añadiendo una cucharada de aceite.',
      'Mientras tanto picamos el chorizo y el tocino y lo freímos (sin aceite) en una sartén pequeña. Cuando estén doraditos los sacamos y reservamos.',
      'Hacemos un sofrito con ajo picado, pimentón y el jugo que nos ha sobrado. Después lo dejamos aparte.',
      'Una vez bien cocidas, colamos las patatas retirando el laurel y el ajo, y guardamos el agua en que cocieron.',
      'Echamos el aceite del sofrito en las patatas mezclando y hacemos un puré con el pasapuré. Podemos usar el agua de cocción para hacerlo más o menos espeso.',
      'Servimos en caliente en una fuente con pan tostado, acompañado del chorizo y la panceta fritos.',
    ],
    tip: {
      text: 'Este plato hay que parearlo con un buen Rioja, uno un poco fuertecito. En vez de pasapuré también se puede usar un tenedor si lo queremos más espeso.',
      author: 'Truco de Mari',
    },
  },

  {
    id: 'paella-valenciana',
    title: 'Paella Valenciana',
    subtitle: 'El plato más emblemático de la cocina española, con su costra dorada y el aroma del azafrán.',
    servings: 4,
    category: 'arroces',
    page: 35,
    incomplete: true,
    ingredientGroups: [],
    steps: [],
    tip: null,
  },

  {
    id: 'barraquito',
    title: 'Barraquito',
    subtitle: 'Café típico canario, una bomba de azúcar que hace de postre, café y licor todo en uno. Es delicioso pero no hay que abusarlo.',
    servings: 2,
    category: 'bebidas',
    page: 36,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '4 cucharadas de leche condensada',
          '4 cucharadas de licor 43 (o algún licor de café)',
          '2 cucharadas de azúcar moreno',
          '400 ml de café espresso',
          '2 rodajas de limón',
          '2 ramitas de canela',
          '400 ml de leche caliente',
        ],
      },
    ],
    steps: [
      'Prepara dos vasos o tazas de vidrio transparente donde servirás el barraquito.',
      'En la base de cada vaso coloca 2 cucharadas de leche condensada.',
      'Añade 2 cucharadas de licor 43 (o licor de café) en cada vaso, sobre la leche condensada.',
      'Espolvorea 1 cucharada de azúcar moreno en cada vaso, sin mezclar.',
      'Coloca una rodaja de limón en el borde de cada vaso y una ramita de canela dentro.',
      'Con ayuda de una cucharilla, vierte con cuidado 200 ml de café espresso en cada vaso. La cucharilla evita que el café caiga directamente sobre el azúcar y la leche condensada, creando capas diferenciadas.',
      'De nuevo, con la cucharilla, vierte 200 ml de leche caliente en cada vaso. Sirve inmediatamente para que la espuma no se pierda.',
    ],
    tip: {
      text: 'Si se tiene un vaporizador para la leche caliente, la espuma queda siempre mejor. Este café funciona también con grappa con una rodaja de naranja o mandarina.',
      author: 'Truco de Jaime',
    },
  },

  {
    id: 'ensalada-espinacas-datiles',
    title: 'Ensalada de Espinacas con Dátiles y Almendras',
    titleEn: 'Baby Spinach Salad with Dates & Almonds',
    subtitle: 'En Jerusalén, la pita tiene la vida útil más corta de todos los alimentos. Lo ideal es comerla pocas horas después de hornearla. Los crutones de pita crujiente dan buen uso a la pita sobrante. Los usamos en sopas y los esparcimos sobre ensaladas y otros mezzes. Aguantan al menos una semana en un recipiente hermético. Sirve esta ensalada como entrante; su frescor intenso abre el apetito.',
    subtitleEn: 'Pitas are allotted the shortest of shelf lives in Jerusalem. Ideally, you\'d eat them within a couple of hours of baking. Crunchy pita croutons make good use of leftover pita. We use them for soups and scatter them over salads and other mezes. They will keep for at least a week in an airtight container. Serve this salad as a starter; its sharp freshness really whets the appetite.',
    servings: 4,
    category: 'aperitivos',
    page: 38,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: [
          '1 cucharada de vinagre de vino blanco',
          '½ cebolla roja mediana, en rodajas finas',
          '100 g de dátiles Medjool deshuesados, en cuartos a lo largo',
          '30 g de mantequilla sin sal',
          '2 cucharadas de aceite de oliva',
          '2 pitas pequeñas (~100 g), troceadas en trozos de 4 cm',
          '75 g de almendras enteras sin sal, picadas en trozos grandes',
          '2 cucharaditas de sumac',
          '½ cucharadita de copos de guindilla',
          '150 g de hojas de espinacas baby',
          '2 cucharadas de zumo de limón recién exprimido',
          'Sal',
        ],
      },
    ],
    ingredientGroupsEn: [
      {
        name: 'Ingredients',
        items: [
          '1 tbsp white wine vinegar',
          '½ medium red onion, thinly sliced',
          '100 g pitted Medjool dates, quartered lengthwise',
          '30 g unsalted butter',
          '2 tbsp olive oil',
          '2 small pitas (~100 g), roughly torn into 4 cm pieces',
          '75 g whole unsalted almonds, coarsely chopped',
          '2 tsp sumac',
          '½ tsp chile flakes',
          '150 g baby spinach leaves',
          '2 tbsp freshly squeezed lemon juice',
          'Salt',
        ],
      },
    ],
    steps: [
      'Pon el vinagre, la cebolla y los dátiles en un bol pequeño. Añade una pizca de sal y mezcla bien con las manos. Deja marinar 20 minutos y escurre el vinagre sobrante.',
      'Mientras tanto, calienta la mantequilla y la mitad del aceite de oliva en una sartén mediana a fuego medio. Añade la pita y las almendras y cocina 4–6 minutos, removiendo constantemente, hasta que la pita esté crujiente y dorada. Retira del fuego e incorpora el sumac, los copos de guindilla y ¼ de cucharadita de sal. Deja enfriar.',
      'Cuando vayas a servir, mezcla las hojas de espinacas con la mezcla de pita en un bol grande. Añade los dátiles y la cebolla escurridos, el aceite de oliva restante, el zumo de limón y otra pizca de sal. Comprueba el punto de sal y sirve inmediatamente.',
    ],
    stepsEn: [
      'Put the vinegar, onion, and dates in a small bowl. Add a pinch of salt and mix well with your hands. Leave to marinate for 20 minutes, then drain any residual vinegar.',
      'Meanwhile, heat the butter and half the olive oil in a medium frying pan over medium heat. Add the pita and almonds and cook for 4–6 minutes, stirring all the time, until the pita is crunchy and golden brown. Remove from the heat and mix in the sumac, chile flakes, and ¼ tsp salt. Set aside to cool.',
      'When ready to serve, toss the spinach leaves with the pita mix in a large bowl. Add the drained dates and onion, the remaining olive oil, the lemon juice, and another pinch of salt. Taste for seasoning and serve immediately.',
    ],
    tip: {
      text: 'El sumac es una especia rojiza con sabor ácido y afrutado, muy usada en la cocina de Oriente Próximo. Se encuentra en tiendas especializadas o en línea. La pita crujiente se puede preparar con antelación y aguanta una semana en un tarro hermético.',
      author: 'Receta de Ottolenghi',
    },
    tipEn: {
      text: 'Sumac is a dark red, tangy spice common in Middle Eastern cooking. It can be found at specialty food stores or online. The crunchy pita can be made ahead and keeps well in an airtight jar for up to a week.',
      author: 'Ottolenghi recipe',
    },
  },

  {
    id: 'dos-huevos-duros',
    title: 'Y También Dos Huevos Duros',
    subtitle: 'Frase de la película "Una noche en la ópera" de los Hermanos Marx y una de las frases favoritas de mi padre cuando pedíamos demasiado.',
    servings: 1,
    category: 'basicos',
    page: 37,
    ingredientGroups: [
      {
        name: 'Ingredientes',
        items: ['1 huevo fresco', 'Otro huevo fresco'],
      },
    ],
    steps: [
      'Se meten los dos huevos en agua y se pone a hervir.',
      'A los 2 minutos y 30 segundos estarán listos para ser comidos mojando pan, muy líquidos. Se sirven con un poquito de sal y pimienta.',
      'A los 3 minutos estarán aún perfectos para mojar pan y rebañar con una cuchara el borde cocido.',
      'A los 5 minutos están listos para hacer una salmuera o tomarlos con soja. Se pelan, se ponen en una cazuela con soja y se cuecen uno o dos minutos más. Se pueden usar para acompañar el arroz.',
      'Más de 6 minutos y estarán ya cocidos. Llévatelos para picar algo cuando tengas que esperar al autobús, o dando un paseo o en cualquier otro momento.',
    ],
    tip: {
      text: 'La receta más sencilla del libro. El tiempo exacto de cocción depende del tamaño del huevo y de si empieza en agua fría o caliente. Experimenta hasta dar con tu punto preferido.',
      author: 'Truco de Alberto',
    },
  },
];
